version: '3.2'

services:

  speaker-diarization:
    container_name: speaker-diarization-worker
    build: .
    image: lintoai/linto-platform-speaker-diarization-worker:latest
    volumes:
      - ${LOGS_PATH}:/opt/logs
      - ${SWAGGER_PATH}:/opt/swagger/
    ports:
      - target: 80
        published: 8888
    env_file: .env