version: '3.2'

services:

  speaker-diarization:
    container_name: speaker-diarization-worker
    build: .
<<<<<<< HEAD
    image: lintoai/linto-platform-speaker-diarization-worker:latest
=======
    image: lintoai/linto-platform-speaker-diarization-worker:latest-unstable
    volumes:
      - ${LOGS_PATH}:/opt/logs
>>>>>>> next
    ports:
      - target: 80
        published: 8888
    env_file: .env